version: "3"
services:
  server:
    build: .
    ports:
      - "8050:8050"
    # Removed the UV_RUN_SERVER environment variable

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - server
    command: http server:8050